'api':
    'base_url': 'https://microcks.gin.dev.securingsam.io/rest/Reputation+API/1.0.0'
    'auth_token': 'I_am_under_stress_when_I_test'
    'timeout': 5
    'max_retries': 3
    'retry_delay': 1

'performance':
    'max_concurrent_requests': 50
    'requests_per_second': 100
    'cache_ttl': 3600

'monitoring':
    'update_interval': 1

'output':
    'results_file': 'dns_reputation_results'
    'format': 'csv'